  %%{init: {'theme':'neutral'}}%%
  %%{config: {'arrowMarkerAbsolute': false}}%%
  graph TD
    A[User] --> B[Sistem e-learning berbasis website]
    B --> C[Mux API]
    B --> D[State based code editor]
    B --> E[Q&A API with OpenAI]
    B --> F[Database]

